name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python version
        run: python --version

      - name: Print installed packages
        run: pip list

      - name: Lint with Flake8
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 --count --max-complexity=10 --max-line-length=127 --statistics .

      - name: Run unit tests with Nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Print test coverage
        run: |
          coverage report -m
