name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.9-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: |
          python -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics .
          python -m flake8 --count --max-complexity=10 --max-line-length=127 --statistics .

      - name: Run unit tests with Nose
        run: |
          python -m nose -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Print test coverage
        run: |
          coverage report -m
